# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(400, 210)
        self.LoginButton = QtWidgets.QPushButton(parent=LoginForm)
        self.LoginButton.setGeometry(QtCore.QRect(310, 180, 75, 30))
        self.LoginButton.setObjectName("LoginButton")
        self.UsernameInput = QtWidgets.QLineEdit(parent=LoginForm)
        self.UsernameInput.setGeometry(QtCore.QRect(20, 80, 361, 20))
        self.UsernameInput.setInputMask("")
        self.UsernameInput.setText("")
        self.UsernameInput.setObjectName("UsernameInput")
        self.PasswordInput = QtWidgets.QLineEdit(parent=LoginForm)
        self.PasswordInput.setGeometry(QtCore.QRect(20, 130, 361, 20))
        self.PasswordInput.setObjectName("PasswordInput")
        self.UsernameLabel = QtWidgets.QLabel(parent=LoginForm)
        self.UsernameLabel.setGeometry(QtCore.QRect(20, 60, 61, 16))
        self.UsernameLabel.setObjectName("UsernameLabel")
        self.PasswordText = QtWidgets.QLabel(parent=LoginForm)
        self.PasswordText.setGeometry(QtCore.QRect(20, 110, 51, 16))
        self.PasswordText.setObjectName("PasswordText")
        self.RememberMeCheckBox = QtWidgets.QCheckBox(parent=LoginForm)
        self.RememberMeCheckBox.setGeometry(QtCore.QRect(20, 160, 100, 17))
        self.RememberMeCheckBox.setObjectName("RememberMeCheckBox")
        self.ImagePicture = QtWidgets.QLabel(parent=LoginForm)
        self.ImagePicture.setGeometry(QtCore.QRect(175, 10, 40, 40))
        # self.ImagePicture.setStyleSheet("image: url(../Resources/icons8-user-50.png);")
        self.ImagePicture.setText("")
        self.ImagePicture.setObjectName("ImagePicture")
        self.LoginText = QtWidgets.QLabel(parent=LoginForm)
        self.LoginText.setGeometry(QtCore.QRect(170, 50, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.LoginText.setFont(font)
        self.LoginText.setObjectName("LoginText")

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "Login"))
        self.LoginButton.setText(_translate("LoginForm", "Login"))
        self.UsernameLabel.setText(_translate("LoginForm", "Username:"))
        self.PasswordText.setText(_translate("LoginForm", "Password:"))
        self.RememberMeCheckBox.setText(_translate("LoginForm", "Remember me"))
        self.LoginText.setText(_translate("LoginForm", "LOGIN"))
